{% set name = "nomad-camels-driver-swabianinstruments-timetagger" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nomad_camels_driver_swabianinstruments_timetagger-{{ version }}.tar.gz
  sha256: 1debbd3d46d4e4ea1c90fed06e5f31234294559b6df8722a233c49c647ad1a97

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - nomad-camels

test:
  requires:
    - python {{ python_min }}
  imports:
    - nomad_camels_driver_swabianinstruments_timetagger

about:
  home: https://github.com/FAU-LAP/CAMELS_drivers
  summary: Instrument driver for a SwabianInstruments TimeTagger for NOMAD-CAMELS
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
